# Generated by Django 3.2 on 2021-04-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0027_branch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
